name: Karaoke
version: '${version}'
main: me.Luki.karaoke.Karaoke
api-version: '1.21'
load: POSTWORLD
authors: [ Luki & StreamCraft ]
description: Link-based karaoke with hologram lyrics and optional Simple Voice Chat music playback

dependencies:
  server:
    FancyHolograms:
      required: true
      load: BEFORE
      join-classpath: true
    voicechat:
      required: true
      load: BEFORE
      join-classpath: true

permissions:

  karaoke.use:
    description: Allows using /karaoke
    default: op

  karaoke.admin:
    description: Allows using /karaokeadmin
    default: op
