name: Karaoke
version: '${version}'
main: me.Luki.karaoke.Karaoke
api-version: '1.21'
load: STARTUP
authors: [ Luki & StreamCraft ]
description: Link-based karaoke with hologram lyrics and optional Simple Voice Chat music playback
softdepend: [ voicechat, FancyHolograms ]

commands:

  karaoke:
    description: Start karaoke from a link (YouTube/Spotify/etc)
    usage: "/karaoke <link|stop> <czerwony|zielony|niebieski>"
    permission: karaoke.use

  karaokeadmin:
    description: Admin commands for Karaoke
    usage: "/karaokeadmin <reload|stopall|debug|http|status>"
    permission: karaoke.admin

permissions:

  karaoke.use:
    description: Allows using /karaoke
    default: op

  karaoke.admin:
    description: Allows using /karaokeadmin
    default: op
